# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QDockWidget,
    QFormLayout, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QTableWidget, QTableWidgetItem, QTextBrowser, QToolBar,
    QVBoxLayout, QWidget)
from frontend.ui import toolicons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1015, 782)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/icons/icons/createnew.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew.setIcon(icon)
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionGerman = QAction(MainWindow)
        self.actionGerman.setObjectName(u"actionGerman")
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/delete.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete.setIcon(icon1)
        self.actionSaveChange = QAction(MainWindow)
        self.actionSaveChange.setObjectName(u"actionSaveChange")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/savechange.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSaveChange.setIcon(icon2)
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/refresh.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRefresh.setIcon(icon3)
        self.actionActive = QAction(MainWindow)
        self.actionActive.setObjectName(u"actionActive")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/active.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionActive.setIcon(icon4)
        self.actionSelectAll = QAction(MainWindow)
        self.actionSelectAll.setObjectName(u"actionSelectAll")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/checkall.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSelectAll.setIcon(icon5)
        self.actionFilter = QAction(MainWindow)
        self.actionFilter.setObjectName(u"actionFilter")
        self.actionFilter.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/filter.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFilter.setIcon(icon6)
        self.actionFilter.setIconVisibleInMenu(False)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionInformation = QAction(MainWindow)
        self.actionInformation.setObjectName(u"actionInformation")
        self.actionInformation.setCheckable(True)
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/information.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionInformation.setIcon(icon7)
        self.actionInformation.setIconVisibleInMenu(False)
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/import.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImport.setIcon(icon8)
        self.actionAttach = QAction(MainWindow)
        self.actionAttach.setObjectName(u"actionAttach")
        icon9 = QIcon()
        icon9.addFile(u":/icons/icons/attach.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAttach.setIcon(icon9)
        self.actionReplace = QAction(MainWindow)
        self.actionReplace.setObjectName(u"actionReplace")
        icon10 = QIcon()
        icon10.addFile(u":/icons/icons/replace.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionReplace.setIcon(icon10)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon11 = QIcon()
        icon11.addFile(u":/icons/icons/copy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCopy.setIcon(icon11)
        self.actionNewDatabase = QAction(MainWindow)
        self.actionNewDatabase.setObjectName(u"actionNewDatabase")
        self.actionConnectDatabase = QAction(MainWindow)
        self.actionConnectDatabase.setObjectName(u"actionConnectDatabase")
        self.actionDeactive = QAction(MainWindow)
        self.actionDeactive.setObjectName(u"actionDeactive")
        icon12 = QIcon()
        icon12.addFile(u":/icons/icons/deactive.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDeactive.setIcon(icon12)
        self.actionSearch = QAction(MainWindow)
        self.actionSearch.setObjectName(u"actionSearch")
        self.actionSearch.setCheckable(True)
        icon13 = QIcon()
        icon13.addFile(u":/icons/icons/search.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSearch.setIcon(icon13)
        self.actionSearch.setIconVisibleInMenu(False)
        self.actionImportDatabase = QAction(MainWindow)
        self.actionImportDatabase.setObjectName(u"actionImportDatabase")
        self.actionRenameSensor = QAction(MainWindow)
        self.actionRenameSensor.setObjectName(u"actionRenameSensor")
        self.actionQuickImport = QAction(MainWindow)
        self.actionQuickImport.setObjectName(u"actionQuickImport")
        self.actionUpdateDBKeyfile = QAction(MainWindow)
        self.actionUpdateDBKeyfile.setObjectName(u"actionUpdateDBKeyfile")
        self.actionUSBLoad = QAction(MainWindow)
        self.actionUSBLoad.setObjectName(u"actionUSBLoad")
        self.actionRemove = QAction(MainWindow)
        self.actionRemove.setObjectName(u"actionRemove")
        icon14 = QIcon()
        icon14.addFile(u":/icons/icons/remove.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRemove.setIcon(icon14)
        self.actionRemove.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)

        self.verticalLayout_2.addWidget(self.tableWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.infoDockWidget = QDockWidget(MainWindow)
        self.infoDockWidget.setObjectName(u"infoDockWidget")
        self.infoDockWidget.setMinimumSize(QSize(79, 100))
        self.infoDockWidget.setMaximumSize(QSize(524287, 524287))
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout_3 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.infoTextBrowser = QTextBrowser(self.dockWidgetContents)
        self.infoTextBrowser.setObjectName(u"infoTextBrowser")

        self.verticalLayout_3.addWidget(self.infoTextBrowser)

        self.infoDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.infoDockWidget)
        self.filterDockWidget = QDockWidget(MainWindow)
        self.filterDockWidget.setObjectName(u"filterDockWidget")
        self.filterDockWidget.setMinimumSize(QSize(189, 287))
        self.filterDockWidget.setMaximumSize(QSize(524287, 524287))
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.verticalLayout = QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName(u"formLayout")
        self.serialNumberLabel = QLabel(self.dockWidgetContents_2)
        self.serialNumberLabel.setObjectName(u"serialNumberLabel")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.serialNumberLabel)

        self.serialNumberLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.serialNumberLineEdit.setObjectName(u"serialNumberLineEdit")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.serialNumberLineEdit)

        self.nameLabel = QLabel(self.dockWidgetContents_2)
        self.nameLabel.setObjectName(u"nameLabel")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.nameLabel)

        self.nameLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.nameLineEdit.setObjectName(u"nameLineEdit")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.nameLineEdit)

        self.projectLabel = QLabel(self.dockWidgetContents_2)
        self.projectLabel.setObjectName(u"projectLabel")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.projectLabel)

        self.projectLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.projectLineEdit.setObjectName(u"projectLineEdit")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.projectLineEdit)

        self.operatorLabel = QLabel(self.dockWidgetContents_2)
        self.operatorLabel.setObjectName(u"operatorLabel")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.operatorLabel)

        self.operatorLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.operatorLineEdit.setObjectName(u"operatorLineEdit")

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.operatorLineEdit)

        self.specimenLabel = QLabel(self.dockWidgetContents_2)
        self.specimenLabel.setObjectName(u"specimenLabel")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.specimenLabel)

        self.specimenLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.specimenLineEdit.setObjectName(u"specimenLineEdit")

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.specimenLineEdit)

        self.dfosTypeLabel = QLabel(self.dockWidgetContents_2)
        self.dfosTypeLabel.setObjectName(u"dfosTypeLabel")

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.dfosTypeLabel)

        self.dFOS_TypeLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.dFOS_TypeLineEdit.setObjectName(u"dFOS_TypeLineEdit")

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.dFOS_TypeLineEdit)

        self.keyfileLabel = QLabel(self.dockWidgetContents_2)
        self.keyfileLabel.setObjectName(u"keyfileLabel")

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.keyfileLabel)

        self.keyfileLineEdit = QLineEdit(self.dockWidgetContents_2)
        self.keyfileLineEdit.setObjectName(u"keyfileLineEdit")

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.keyfileLineEdit)

        self.stateLabel = QLabel(self.dockWidgetContents_2)
        self.stateLabel.setObjectName(u"stateLabel")

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.stateLabel)

        self.stateComboBox = QComboBox(self.dockWidgetContents_2)
        self.stateComboBox.setObjectName(u"stateComboBox")

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.stateComboBox)


        self.verticalLayout.addLayout(self.formLayout)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.cancelButton = QPushButton(self.dockWidgetContents_2)
        self.cancelButton.setObjectName(u"cancelButton")

        self.horizontalLayout.addWidget(self.cancelButton)

        self.filterButton = QPushButton(self.dockWidgetContents_2)
        self.filterButton.setObjectName(u"filterButton")

        self.horizontalLayout.addWidget(self.filterButton)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.filterDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.filterDockWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1015, 33))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuSetting = QMenu(self.menuBar)
        self.menuSetting.setObjectName(u"menuSetting")
        self.menuLanguage = QMenu(self.menuSetting)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuSensors = QMenu(self.menuBar)
        self.menuSensors.setObjectName(u"menuSensors")
        MainWindow.setMenuBar(self.menuBar)
        self.searchDockWidget = QDockWidget(MainWindow)
        self.searchDockWidget.setObjectName(u"searchDockWidget")
        self.searchDockWidget.setMinimumSize(QSize(146, 159))
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.verticalLayout_4 = QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.searchComboBox = QComboBox(self.dockWidgetContents_3)
        self.searchComboBox.setObjectName(u"searchComboBox")

        self.verticalLayout_4.addWidget(self.searchComboBox)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.searchLineEdit = QLineEdit(self.dockWidgetContents_3)
        self.searchLineEdit.setObjectName(u"searchLineEdit")

        self.horizontalLayout_2.addWidget(self.searchLineEdit)

        self.searchPushButton = QPushButton(self.dockWidgetContents_3)
        self.searchPushButton.setObjectName(u"searchPushButton")

        self.horizontalLayout_2.addWidget(self.searchPushButton)


        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.searchTextBrowser = QTextBrowser(self.dockWidgetContents_3)
        self.searchTextBrowser.setObjectName(u"searchTextBrowser")

        self.verticalLayout_4.addWidget(self.searchTextBrowser)

        self.searchDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.searchDockWidget)

        self.toolBar.addAction(self.actionSelectAll)
        self.toolBar.addAction(self.actionActive)
        self.toolBar.addAction(self.actionDeactive)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionSaveChange)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImport)
        self.toolBar.addAction(self.actionAttach)
        self.toolBar.addAction(self.actionReplace)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionRemove)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFilter)
        self.toolBar.addAction(self.actionInformation)
        self.toolBar.addAction(self.actionSearch)
        self.toolBar.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSensors.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNewDatabase)
        self.menuFile.addAction(self.actionConnectDatabase)
        self.menuFile.addAction(self.actionImportDatabase)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveChange)
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionInformation)
        self.menuView.addAction(self.actionFilter)
        self.menuView.addAction(self.actionSearch)
        self.menuSetting.addAction(self.actionOpen)
        self.menuSetting.addAction(self.menuLanguage.menuAction())
        self.menuLanguage.addAction(self.actionGerman)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuSensors.addAction(self.actionUSBLoad)
        self.menuSensors.addAction(self.actionQuickImport)
        self.menuSensors.addAction(self.actionRenameSensor)
        self.menuSensors.addAction(self.actionUpdateDBKeyfile)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"fosKeyMan", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"New row", None))
#endif // QT_CONFIG(tooltip)
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionGerman.setText(QCoreApplication.translate("MainWindow", u"German", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindow", u"Documentation", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
#if QT_CONFIG(tooltip)
        self.actionDelete.setToolTip(QCoreApplication.translate("MainWindow", u"Delete row", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveChange.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSaveChange.setToolTip(QCoreApplication.translate("MainWindow", u"Save Change", None))
#endif // QT_CONFIG(tooltip)
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.actionRefresh.setToolTip(QCoreApplication.translate("MainWindow", u"Refresh", None))
#endif // QT_CONFIG(tooltip)
        self.actionActive.setText(QCoreApplication.translate("MainWindow", u"Activated", None))
#if QT_CONFIG(tooltip)
        self.actionActive.setToolTip(QCoreApplication.translate("MainWindow", u"Actived", None))
#endif // QT_CONFIG(tooltip)
        self.actionSelectAll.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
#if QT_CONFIG(tooltip)
        self.actionSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"Select All", None))
#endif // QT_CONFIG(tooltip)
        self.actionFilter.setText(QCoreApplication.translate("MainWindow", u"Filter", None))
#if QT_CONFIG(tooltip)
        self.actionFilter.setToolTip(QCoreApplication.translate("MainWindow", u"Filter", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Connection Settings", None))
        self.actionInformation.setText(QCoreApplication.translate("MainWindow", u"Information", None))
#if QT_CONFIG(tooltip)
        self.actionInformation.setToolTip(QCoreApplication.translate("MainWindow", u"More information", None))
#endif // QT_CONFIG(tooltip)
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
#if QT_CONFIG(tooltip)
        self.actionImport.setToolTip(QCoreApplication.translate("MainWindow", u"Import to database", None))
#endif // QT_CONFIG(tooltip)
        self.actionAttach.setText(QCoreApplication.translate("MainWindow", u"Attach", None))
#if QT_CONFIG(tooltip)
        self.actionAttach.setToolTip(QCoreApplication.translate("MainWindow", u"Attach keyfile", None))
#endif // QT_CONFIG(tooltip)
        self.actionReplace.setText(QCoreApplication.translate("MainWindow", u"Replace", None))
#if QT_CONFIG(tooltip)
        self.actionReplace.setToolTip(QCoreApplication.translate("MainWindow", u"Replace Keyfile", None))
#endif // QT_CONFIG(tooltip)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(tooltip)
        self.actionCopy.setToolTip(QCoreApplication.translate("MainWindow", u"Copy Keyfile to Disk", None))
#endif // QT_CONFIG(tooltip)
        self.actionNewDatabase.setText(QCoreApplication.translate("MainWindow", u"New Database", None))
#if QT_CONFIG(tooltip)
        self.actionNewDatabase.setToolTip(QCoreApplication.translate("MainWindow", u"Create a new Database", None))
#endif // QT_CONFIG(tooltip)
        self.actionConnectDatabase.setText(QCoreApplication.translate("MainWindow", u"Connect Database", None))
#if QT_CONFIG(tooltip)
        self.actionConnectDatabase.setToolTip(QCoreApplication.translate("MainWindow", u"Connect to a Database", None))
#endif // QT_CONFIG(tooltip)
        self.actionDeactive.setText(QCoreApplication.translate("MainWindow", u"Dactivated", None))
#if QT_CONFIG(tooltip)
        self.actionDeactive.setToolTip(QCoreApplication.translate("MainWindow", u"Deactived", None))
#endif // QT_CONFIG(tooltip)
        self.actionSearch.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(tooltip)
        self.actionSearch.setToolTip(QCoreApplication.translate("MainWindow", u"Full Text Search", None))
#endif // QT_CONFIG(tooltip)
        self.actionImportDatabase.setText(QCoreApplication.translate("MainWindow", u"Import Database", None))
#if QT_CONFIG(tooltip)
        self.actionImportDatabase.setToolTip(QCoreApplication.translate("MainWindow", u"Import a Database into Current", None))
#endif // QT_CONFIG(tooltip)
        self.actionRenameSensor.setText(QCoreApplication.translate("MainWindow", u"Rename Sensor", None))
#if QT_CONFIG(tooltip)
        self.actionRenameSensor.setToolTip(QCoreApplication.translate("MainWindow", u"Rename Sensor Name", None))
#endif // QT_CONFIG(tooltip)
        self.actionQuickImport.setText(QCoreApplication.translate("MainWindow", u"Quick Import", None))
#if QT_CONFIG(tooltip)
        self.actionQuickImport.setToolTip(QCoreApplication.translate("MainWindow", u"Quick import all missing keyfiles into the database", None))
#endif // QT_CONFIG(tooltip)
        self.actionUpdateDBKeyfile.setText(QCoreApplication.translate("MainWindow", u"Update DB Keyfile", None))
#if QT_CONFIG(tooltip)
        self.actionUpdateDBKeyfile.setToolTip(QCoreApplication.translate("MainWindow", u"Update attached Keyfile in Database", None))
#endif // QT_CONFIG(tooltip)
        self.actionUSBLoad.setText(QCoreApplication.translate("MainWindow", u"Load from USB", None))
#if QT_CONFIG(tooltip)
        self.actionUSBLoad.setToolTip(QCoreApplication.translate("MainWindow", u"Load Key Files from USB", None))
#endif // QT_CONFIG(tooltip)
        self.actionRemove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
#if QT_CONFIG(tooltip)
        self.tableWidget.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBar.setToolTip(QCoreApplication.translate("MainWindow", u"Tools", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.infoDockWidget.setToolTip(QCoreApplication.translate("MainWindow", u"Display more details about the selected item", None))
#endif // QT_CONFIG(tooltip)
        self.infoDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Information", None))
#if QT_CONFIG(tooltip)
        self.infoTextBrowser.setToolTip(QCoreApplication.translate("MainWindow", u"More information about the selected record", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.filterDockWidget.setToolTip(QCoreApplication.translate("MainWindow", u"Filter content based on specified criteria", None))
#endif // QT_CONFIG(tooltip)
        self.filterDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Content Filter", None))
#if QT_CONFIG(tooltip)
        self.serialNumberLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Serial Number", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.serialNumberLabel.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.serialNumberLabel.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.serialNumberLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.serialNumberLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.serialNumberLabel.setText(QCoreApplication.translate("MainWindow", u"Serial Number", None))
#if QT_CONFIG(tooltip)
        self.serialNumberLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter serial number to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.nameLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Sensor Name", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.nameLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.nameLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.nameLabel.setText(QCoreApplication.translate("MainWindow", u"Sensor Name", None))
#if QT_CONFIG(tooltip)
        self.nameLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter name to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.projectLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Project", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.projectLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.projectLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.projectLabel.setText(QCoreApplication.translate("MainWindow", u"Project", None))
#if QT_CONFIG(tooltip)
        self.projectLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter project name to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.operatorLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Operator", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.operatorLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.operatorLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.operatorLabel.setText(QCoreApplication.translate("MainWindow", u"Operator", None))
#if QT_CONFIG(tooltip)
        self.operatorLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter operator name to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.specimenLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Specimen", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.specimenLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.specimenLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.specimenLabel.setText(QCoreApplication.translate("MainWindow", u"Specimen", None))
#if QT_CONFIG(tooltip)
        self.specimenLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter specimen name to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.dfosTypeLabel.setToolTip(QCoreApplication.translate("MainWindow", u"DFOS Type", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.dfosTypeLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.dfosTypeLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.dfosTypeLabel.setText(QCoreApplication.translate("MainWindow", u"DFOS_Type", None))
#if QT_CONFIG(tooltip)
        self.dFOS_TypeLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter DFOS type to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.keyfileLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Keyfile", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.keyfileLabel.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.keyfileLabel.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.keyfileLabel.setText(QCoreApplication.translate("MainWindow", u"Keyfile", None))
#if QT_CONFIG(tooltip)
        self.keyfileLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Enter keyfile name to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.stateLabel.setToolTip(QCoreApplication.translate("MainWindow", u"Status", None))
#endif // QT_CONFIG(tooltip)
        self.stateLabel.setText(QCoreApplication.translate("MainWindow", u"Status", None))
#if QT_CONFIG(tooltip)
        self.stateComboBox.setToolTip(QCoreApplication.translate("MainWindow", u"Select keyfile status to filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.cancelButton.setToolTip(QCoreApplication.translate("MainWindow", u"Clear filter and reset", None))
#endif // QT_CONFIG(tooltip)
        self.cancelButton.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
#if QT_CONFIG(tooltip)
        self.filterButton.setToolTip(QCoreApplication.translate("MainWindow", u"Apply filter based on the entered criteria", None))
#endif // QT_CONFIG(tooltip)
        self.filterButton.setText(QCoreApplication.translate("MainWindow", u"Filter", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuSetting.setTitle(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
        self.menuSensors.setTitle(QCoreApplication.translate("MainWindow", u"Sensors ", None))
#if QT_CONFIG(tooltip)
        self.searchDockWidget.setToolTip(QCoreApplication.translate("MainWindow", u"Full Text Search", None))
#endif // QT_CONFIG(tooltip)
        self.searchDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Full Text Search", None))
#if QT_CONFIG(tooltip)
        self.searchComboBox.setToolTip(QCoreApplication.translate("MainWindow", u"Select Search Keyfile", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.searchLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Search", None))
#endif // QT_CONFIG(tooltip)
        self.searchLineEdit.setText("")
#if QT_CONFIG(tooltip)
        self.searchPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Full text seach in selected keyfile", None))
#endif // QT_CONFIG(tooltip)
        self.searchPushButton.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(tooltip)
        self.searchTextBrowser.setToolTip(QCoreApplication.translate("MainWindow", u"Search Result", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

