# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QDockWidget,
    QFormLayout, QHBoxLayout, QHeaderView, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QStatusBar, QTableWidget,
    QTableWidgetItem, QTextBrowser, QToolBar, QVBoxLayout,
    QWidget)
from frontend.ui import toolicons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(773, 782)
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionGerman = QAction(MainWindow)
        self.actionGerman.setObjectName(u"actionGerman")
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        icon = QIcon()
        icon.addFile(u":/icons/icons/editbin.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete.setIcon(icon)
        self.actionSaveChange = QAction(MainWindow)
        self.actionSaveChange.setObjectName(u"actionSaveChange")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/savechange.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSaveChange.setIcon(icon1)
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/refresh.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRefresh.setIcon(icon2)
        self.actionActive = QAction(MainWindow)
        self.actionActive.setObjectName(u"actionActive")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/active.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionActive.setIcon(icon3)
        self.actionSelectAll = QAction(MainWindow)
        self.actionSelectAll.setObjectName(u"actionSelectAll")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/checkall.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSelectAll.setIcon(icon4)
        self.actionFilter = QAction(MainWindow)
        self.actionFilter.setObjectName(u"actionFilter")
        self.actionFilter.setCheckable(True)
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/filter.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFilter.setIcon(icon5)
        self.actionFilter.setIconVisibleInMenu(False)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionInformation = QAction(MainWindow)
        self.actionInformation.setObjectName(u"actionInformation")
        self.actionInformation.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/information.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionInformation.setIcon(icon6)
        self.actionInformation.setIconVisibleInMenu(False)
        self.actionDeactive = QAction(MainWindow)
        self.actionDeactive.setObjectName(u"actionDeactive")
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/deactive.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDeactive.setIcon(icon7)
        self.actionSearch = QAction(MainWindow)
        self.actionSearch.setObjectName(u"actionSearch")
        self.actionSearch.setCheckable(True)
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/search.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSearch.setIcon(icon8)
        self.actionSearch.setIconVisibleInMenu(False)
        self.actionRenameSensor = QAction(MainWindow)
        self.actionRenameSensor.setObjectName(u"actionRenameSensor")
        self.actionImportKeyfiles = QAction(MainWindow)
        self.actionImportKeyfiles.setObjectName(u"actionImportKeyfiles")
        self.actionExportKeyfiles = QAction(MainWindow)
        self.actionExportKeyfiles.setObjectName(u"actionExportKeyfiles")
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        icon9 = QIcon()
        icon9.addFile(u":/icons/icons/edit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionEdit.setIcon(icon9)
        self.actionEdit.setMenuRole(QAction.MenuRole.NoRole)
        self.actionTableColumn = QAction(MainWindow)
        self.actionTableColumn.setObjectName(u"actionTableColumn")
        self.actionDeletedKeyfiles = QAction(MainWindow)
        self.actionDeletedKeyfiles.setObjectName(u"actionDeletedKeyfiles")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)

        self.verticalLayout_2.addWidget(self.tableWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.infoDockWidget = QDockWidget(MainWindow)
        self.infoDockWidget.setObjectName(u"infoDockWidget")
        self.infoDockWidget.setMinimumSize(QSize(79, 100))
        self.infoDockWidget.setMaximumSize(QSize(524287, 524287))
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout_3 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.infoTextBrowser = QTextBrowser(self.dockWidgetContents)
        self.infoTextBrowser.setObjectName(u"infoTextBrowser")

        self.verticalLayout_3.addWidget(self.infoTextBrowser)

        self.infoDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.infoDockWidget)
        self.filterDockWidget = QDockWidget(MainWindow)
        self.filterDockWidget.setObjectName(u"filterDockWidget")
        self.filterDockWidget.setMinimumSize(QSize(189, 287))
        self.filterDockWidget.setMaximumSize(QSize(524287, 524287))
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.verticalLayout = QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.scrollArea = QScrollArea(self.dockWidgetContents_2)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 254, 212))
        self.verticalLayout_6 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.filterFormLayout = QFormLayout()
        self.filterFormLayout.setObjectName(u"filterFormLayout")

        self.verticalLayout_6.addLayout(self.filterFormLayout)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.verticalLayout.addWidget(self.scrollArea)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.cancelButton = QPushButton(self.dockWidgetContents_2)
        self.cancelButton.setObjectName(u"cancelButton")

        self.horizontalLayout.addWidget(self.cancelButton)

        self.filterButton = QPushButton(self.dockWidgetContents_2)
        self.filterButton.setObjectName(u"filterButton")

        self.horizontalLayout.addWidget(self.filterButton)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.filterDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.filterDockWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 773, 33))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuSetting = QMenu(self.menuBar)
        self.menuSetting.setObjectName(u"menuSetting")
        self.menuLanguage = QMenu(self.menuSetting)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuSensors = QMenu(self.menuBar)
        self.menuSensors.setObjectName(u"menuSensors")
        MainWindow.setMenuBar(self.menuBar)
        self.searchDockWidget = QDockWidget(MainWindow)
        self.searchDockWidget.setObjectName(u"searchDockWidget")
        self.searchDockWidget.setMinimumSize(QSize(146, 159))
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.verticalLayout_4 = QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.searchComboBox = QComboBox(self.dockWidgetContents_3)
        self.searchComboBox.setObjectName(u"searchComboBox")

        self.verticalLayout_4.addWidget(self.searchComboBox)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.searchLineEdit = QLineEdit(self.dockWidgetContents_3)
        self.searchLineEdit.setObjectName(u"searchLineEdit")

        self.horizontalLayout_2.addWidget(self.searchLineEdit)

        self.searchPushButton = QPushButton(self.dockWidgetContents_3)
        self.searchPushButton.setObjectName(u"searchPushButton")

        self.horizontalLayout_2.addWidget(self.searchPushButton)


        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.searchTextBrowser = QTextBrowser(self.dockWidgetContents_3)
        self.searchTextBrowser.setObjectName(u"searchTextBrowser")

        self.verticalLayout_4.addWidget(self.searchTextBrowser)

        self.searchDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.searchDockWidget)

        self.toolBar.addAction(self.actionSelectAll)
        self.toolBar.addAction(self.actionActive)
        self.toolBar.addAction(self.actionDeactive)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionSaveChange)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFilter)
        self.toolBar.addAction(self.actionInformation)
        self.toolBar.addAction(self.actionSearch)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSensors.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSaveChange)
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionInformation)
        self.menuView.addAction(self.actionFilter)
        self.menuView.addAction(self.actionSearch)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionTableColumn)
        self.menuSetting.addAction(self.actionOpen)
        self.menuSetting.addAction(self.menuLanguage.menuAction())
        self.menuLanguage.addAction(self.actionGerman)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuSensors.addAction(self.actionImportKeyfiles)
        self.menuSensors.addAction(self.actionExportKeyfiles)
        self.menuSensors.addAction(self.actionDeletedKeyfiles)
        self.menuSensors.addAction(self.actionRenameSensor)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"fosKeyMan", None))
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionGerman.setText(QCoreApplication.translate("MainWindow", u"German", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindow", u"Documentation", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
#if QT_CONFIG(tooltip)
        self.actionDelete.setToolTip(QCoreApplication.translate("MainWindow", u"Delete row", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveChange.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSaveChange.setToolTip(QCoreApplication.translate("MainWindow", u"Save Change", None))
#endif // QT_CONFIG(tooltip)
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.actionRefresh.setToolTip(QCoreApplication.translate("MainWindow", u"Refresh", None))
#endif // QT_CONFIG(tooltip)
        self.actionActive.setText(QCoreApplication.translate("MainWindow", u"Activated", None))
#if QT_CONFIG(tooltip)
        self.actionActive.setToolTip(QCoreApplication.translate("MainWindow", u"Actived", None))
#endif // QT_CONFIG(tooltip)
        self.actionSelectAll.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
#if QT_CONFIG(tooltip)
        self.actionSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"Select All", None))
#endif // QT_CONFIG(tooltip)
        self.actionFilter.setText(QCoreApplication.translate("MainWindow", u"Filter", None))
#if QT_CONFIG(tooltip)
        self.actionFilter.setToolTip(QCoreApplication.translate("MainWindow", u"Filter", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Connection Settings", None))
        self.actionInformation.setText(QCoreApplication.translate("MainWindow", u"Information", None))
#if QT_CONFIG(tooltip)
        self.actionInformation.setToolTip(QCoreApplication.translate("MainWindow", u"More information", None))
#endif // QT_CONFIG(tooltip)
        self.actionDeactive.setText(QCoreApplication.translate("MainWindow", u"Dactivated", None))
#if QT_CONFIG(tooltip)
        self.actionDeactive.setToolTip(QCoreApplication.translate("MainWindow", u"Deactived", None))
#endif // QT_CONFIG(tooltip)
        self.actionSearch.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(tooltip)
        self.actionSearch.setToolTip(QCoreApplication.translate("MainWindow", u"Full Text Search", None))
#endif // QT_CONFIG(tooltip)
        self.actionRenameSensor.setText(QCoreApplication.translate("MainWindow", u"Rename Sensor", None))
#if QT_CONFIG(tooltip)
        self.actionRenameSensor.setToolTip(QCoreApplication.translate("MainWindow", u"Rename Sensor Name", None))
#endif // QT_CONFIG(tooltip)
        self.actionImportKeyfiles.setText(QCoreApplication.translate("MainWindow", u"Import Keyfiles", None))
#if QT_CONFIG(tooltip)
        self.actionImportKeyfiles.setToolTip(QCoreApplication.translate("MainWindow", u"Load Key Files from USB", None))
#endif // QT_CONFIG(tooltip)
        self.actionExportKeyfiles.setText(QCoreApplication.translate("MainWindow", u"Export Keyfiles", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionTableColumn.setText(QCoreApplication.translate("MainWindow", u"Table Columns", None))
        self.actionDeletedKeyfiles.setText(QCoreApplication.translate("MainWindow", u"Deleted Keyfiles", None))
#if QT_CONFIG(tooltip)
        self.tableWidget.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBar.setToolTip(QCoreApplication.translate("MainWindow", u"Tools", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.infoDockWidget.setToolTip(QCoreApplication.translate("MainWindow", u"Display more details about the selected item", None))
#endif // QT_CONFIG(tooltip)
        self.infoDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Information", None))
#if QT_CONFIG(tooltip)
        self.infoTextBrowser.setToolTip(QCoreApplication.translate("MainWindow", u"More information about the selected record", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.filterDockWidget.setToolTip(QCoreApplication.translate("MainWindow", u"Filter content based on specified criteria", None))
#endif // QT_CONFIG(tooltip)
        self.filterDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Content Filter", None))
#if QT_CONFIG(tooltip)
        self.cancelButton.setToolTip(QCoreApplication.translate("MainWindow", u"Clear filter and reset", None))
#endif // QT_CONFIG(tooltip)
        self.cancelButton.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
#if QT_CONFIG(tooltip)
        self.filterButton.setToolTip(QCoreApplication.translate("MainWindow", u"Apply filter based on the entered criteria", None))
#endif // QT_CONFIG(tooltip)
        self.filterButton.setText(QCoreApplication.translate("MainWindow", u"Filter", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuSetting.setTitle(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
        self.menuSensors.setTitle(QCoreApplication.translate("MainWindow", u"Sensors ", None))
#if QT_CONFIG(tooltip)
        self.searchDockWidget.setToolTip(QCoreApplication.translate("MainWindow", u"Full Text Search", None))
#endif // QT_CONFIG(tooltip)
        self.searchDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Full Text Search", None))
#if QT_CONFIG(tooltip)
        self.searchComboBox.setToolTip(QCoreApplication.translate("MainWindow", u"Select Search Keyfile", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.searchLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Search", None))
#endif // QT_CONFIG(tooltip)
        self.searchLineEdit.setText("")
#if QT_CONFIG(tooltip)
        self.searchPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"Full text seach in selected keyfile", None))
#endif // QT_CONFIG(tooltip)
        self.searchPushButton.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(tooltip)
        self.searchTextBrowser.setToolTip(QCoreApplication.translate("MainWindow", u"Search Result", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

